-- ============================================================================
-- SEED FORMATIONS — migration des 12 cours statiques du front vers Supabase.
-- Généré depuis portfolio-frontend/src/data/courses.tsx.
-- Prix convertis XAF -> EUR (taux 655.957, arrondi à l'euro) : à ajuster
-- librement ensuite via l'onglet admin ou en SQL.
-- Idempotent : les slugs déjà présents sont ignorés.
-- ============================================================================

insert into public.courses (
  slug,
  theme, level,
  title_fr, title_en,
  summary_fr, summary_en,
  prerequisites,
  preview,
  preview_label_fr, preview_label_en,
  price_amount, currency,
  duration_hours,
  instructor,
  rating,
  students_count,
  is_published,
  published_at
) values
(
  $seed$web-react-ts-2026-05-08$seed$,
  $seed$web$seed$, $seed$intermediate$seed$,
  $seed$React & TypeScript : De Zéro à Expert$seed$, $seed$React & TypeScript: Zero to Expert$seed$,
  $seed$Maîtrisez React 18, les hooks avancés, TypeScript et les patterns de composants modernes pour des apps production-ready.$seed$, $seed$Master React 18, advanced hooks, TypeScript, and modern component patterns for production-ready apps.$seed$,
  $seed$[{"fr":"JavaScript ES6+","en":"JavaScript ES6+"},{"fr":"Bases HTML/CSS","en":"HTML/CSS basics"}]$seed$::jsonb,
  $seed${"kind":"code","content":"// Custom hook réutilisable avec TypeScript\nfunction useFetch<T>(url: string) {\n  const [data, setData] = React.useState<T | null>(null);\n  const [loading, setLoading] = React.useState(true);\n  \n  React.useEffect(() => {\n    fetch(url)\n      .then(r => r.json())\n      .then((d: T) => { setData(d); setLoading(false); });\n  }, [url]);\n  \n  return { data, loading };\n}"}$seed$::jsonb,
  $seed$Extrait de composant$seed$, $seed$Component snippet$seed$,
  69, 'EUR',
  35,
  $seed$Valmy MABIKA$seed$,
  4.9,
  312,
  true,
  $seed$2026-05-08$seed$::timestamptz
),
(
  $seed$web-responsive-2026-04-20$seed$,
  $seed$web$seed$, $seed$intermediate$seed$,
  $seed$Responsive Design Avancé avec Tailwind$seed$, $seed$Advanced Responsive Design with Tailwind$seed$,
  $seed$Grilles fluides, breakpoints pratiques et composants adaptatifs orientés produit. Mobile-first de A à Z.$seed$, $seed$Fluid grids, practical breakpoints, and product-oriented adaptive components. Mobile-first from A to Z.$seed$,
  $seed$[{"fr":"HTML/CSS","en":"HTML/CSS"},{"fr":"Bases Tailwind","en":"Tailwind basics"}]$seed$::jsonb,
  $seed${"kind":"code","content":"// React + Tailwind: container responsive\nexport function ResponsiveGrid({ items }: { items: Item[] }) {\n  return (\n    <div className=\"grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4\">\n      {items.map(item => (\n        <div key={item.id}\n          className=\"rounded-xl border p-4 hover:shadow-md transition-all\">\n          {item.title}\n        </div>\n      ))}\n    </div>\n  );\n}"}$seed$::jsonb,
  $seed$Preview code live$seed$, $seed$Live code preview$seed$,
  38, 'EUR',
  20,
  $seed$Valmy MABIKA$seed$,
  4.7,
  198,
  true,
  $seed$2026-04-20$seed$::timestamptz
),
(
  $seed$web-api-nodejs-2026-04-10$seed$,
  $seed$web$seed$, $seed$advanced$seed$,
  $seed$APIs REST Professionnelles avec Node.js$seed$, $seed$Professional REST APIs with Node.js$seed$,
  $seed$Architecture REST, authentification JWT, validation, pagination, tests et documentation Swagger en production.$seed$, $seed$REST architecture, JWT authentication, validation, pagination, testing, and Swagger documentation in production.$seed$,
  $seed$[{"fr":"JavaScript Node.js","en":"JavaScript Node.js"},{"fr":"Bases des BDD","en":"Database basics"}]$seed$::jsonb,
  $seed${"kind":"code","content":"// Middleware d'authentification JWT\nconst authMiddleware = (req, res, next) => {\n  const token = req.headers.authorization?.split(' ')[1];\n  if (!token) return res.status(401).json({ error: 'Unauthorized' });\n  \n  try {\n    const payload = jwt.verify(token, process.env.JWT_SECRET);\n    req.user = payload;\n    next();\n  } catch {\n    res.status(403).json({ error: 'Token invalid' });\n  }\n};"}$seed$::jsonb,
  $seed$Extrait d'API$seed$, $seed$API snippet$seed$,
  61, 'EUR',
  28,
  $seed$Valmy MABIKA$seed$,
  4.8,
  156,
  true,
  $seed$2026-04-10$seed$::timestamptz
),
(
  $seed$web-css-grid-2026-03-15$seed$,
  $seed$web$seed$, $seed$beginner$seed$,
  $seed$CSS Grid & Flexbox Masterclass$seed$, $seed$CSS Grid & Flexbox Masterclass$seed$,
  $seed$Devenez maître du positionnement CSS : Grid bidimensionnel, Flexbox et des layouts pixel-perfect sans framework.$seed$, $seed$Master CSS positioning: two-dimensional Grid, Flexbox, and pixel-perfect layouts without a framework.$seed$,
  $seed$[{"fr":"HTML/CSS basique","en":"Basic HTML/CSS"}]$seed$::jsonb,
  $seed${"kind":"code","content":"/* Layout complexe avec CSS Grid */\n.dashboard {\n  display: grid;\n  grid-template-areas:\n    'sidebar header header'\n    'sidebar main   aside'\n    'sidebar footer footer';\n  grid-template-columns: 240px 1fr 300px;\n  grid-template-rows: 64px 1fr 48px;\n  min-height: 100vh;\n}"}$seed$::jsonb,
  $seed$Layouts interactifs$seed$, $seed$Interactive layouts$seed$,
  23, 'EUR',
  12,
  $seed$Valmy MABIKA$seed$,
  4.6,
  421,
  true,
  $seed$2026-03-15$seed$::timestamptz
),
(
  $seed$python-telegram-2026-05-09$seed$,
  $seed$python$seed$, $seed$beginner$seed$,
  $seed$Bots Telegram Intelligents avec Python$seed$, $seed$Smart Telegram Bots with Python$seed$,
  $seed$Créez des bots Telegram complets : commandes, menus inline, notifications automatiques et intégration d'APIs externes.$seed$, $seed$Build complete Telegram bots: commands, inline menus, automatic notifications, and external API integration.$seed$,
  $seed$[{"fr":"Bases Python","en":"Python basics"}]$seed$::jsonb,
  $seed${"kind":"code","content":"# Bot Telegram avec python-telegram-bot\nfrom telegram.ext import Application, CommandHandler\n\nasync def start(update, context):\n    await update.message.reply_text(\n        '👋 Bonjour ! Je suis votre assistant.\\n'\n        'Tapez /aide pour voir les commandes.'\n    )\n\napp = Application.builder().token(TOKEN).build()\napp.add_handler(CommandHandler('start', start))\napp.run_polling()"}$seed$::jsonb,
  $seed$Démo script exécutable$seed$, $seed$Runnable script demo$seed$,
  27, 'EUR',
  15,
  $seed$Valmy MABIKA$seed$,
  4.7,
  289,
  true,
  $seed$2026-05-09$seed$::timestamptz
),
(
  $seed$python-datascience-2026-04-25$seed$,
  $seed$python$seed$, $seed$intermediate$seed$,
  $seed$Python pour la Data Science$seed$, $seed$Python for Data Science$seed$,
  $seed$NumPy, Pandas, Matplotlib, Scikit-learn : la stack complète pour analyser, visualiser et modéliser vos données.$seed$, $seed$NumPy, Pandas, Matplotlib, Scikit-learn: the complete stack to analyze, visualize, and model your data.$seed$,
  $seed$[{"fr":"Python intermédiaire","en":"Intermediate Python"},{"fr":"Maths de base","en":"Basic math"}]$seed$::jsonb,
  $seed${"kind":"dataset","content":"# Analyse exploratoire avec Pandas\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\ndf = pd.read_csv('ventes.csv')\nprint(df.describe())         # Stats descriptives\nprint(df.isnull().sum())     # Valeurs manquantes\n\n# Évolution mensuelle\ndf.groupby('mois')['ca'].sum().plot(kind='bar')\nplt.title('CA mensuel')\nplt.show()"}$seed$::jsonb,
  $seed$Notebook interactif$seed$, $seed$Interactive notebook$seed$,
  53, 'EUR',
  30,
  $seed$Valmy MABIKA$seed$,
  4.9,
  374,
  true,
  $seed$2026-04-25$seed$::timestamptz
),
(
  $seed$python-rpa-2026-03-20$seed$,
  $seed$python$seed$, $seed$intermediate$seed$,
  $seed$Automatisation RPA avec Python$seed$, $seed$RPA Automation with Python$seed$,
  $seed$Automatisez Excel, les emails, les navigateurs et les formulaires web. Construisez des robots robustes avec logs et gestion d'erreurs.$seed$, $seed$Automate Excel, emails, browsers, and web forms. Build robust robots with logging and error handling.$seed$,
  $seed$[{"fr":"Python intermédiaire","en":"Intermediate Python"}]$seed$::jsonb,
  $seed${"kind":"code","content":"# Automatisation Excel + envoi d'email\nimport openpyxl\nimport smtplib\n\ndef generer_rapport(fichier):\n    wb = openpyxl.load_workbook(fichier)\n    ws = wb.active\n    total = sum(ws[f'C{i}'].value or 0 for i in range(2, ws.max_row+1))\n    return f'Total mensuel: {total:,.0f} €'\n\nrapport = generer_rapport('ventes.xlsx')\nenvoyer_email(rapport)  # → SMTP automatisé"}$seed$::jsonb,
  $seed$Script d'automatisation$seed$, $seed$Automation script$seed$,
  34, 'EUR',
  18,
  $seed$Valmy MABIKA$seed$,
  4.8,
  167,
  true,
  $seed$2026-03-20$seed$::timestamptz
),
(
  $seed$data-pandas-2026-05-10$seed$,
  $seed$data$seed$, $seed$advanced$seed$,
  $seed$Pandas & Visualisation de Données$seed$, $seed$Pandas & Data Visualization$seed$,
  $seed$Du dataset brut au data storytelling : nettoyage, transformations, Plotly, Seaborn et dashboards interactifs.$seed$, $seed$From raw dataset to data storytelling: cleaning, transformations, Plotly, Seaborn, and interactive dashboards.$seed$,
  $seed$[{"fr":"Python","en":"Python"},{"fr":"Statistiques descriptives","en":"Descriptive statistics"}]$seed$::jsonb,
  $seed${"kind":"dataset","content":"date,canal,commandes,ca\n2026-05-01,SEO,18,1430\n2026-05-02,Ads,12,990\n2026-05-03,Referral,6,420\n2026-05-04,Email,10,760\n2026-05-05,Social,22,1870\n2026-05-06,Direct,9,680"}$seed$::jsonb,
  $seed$Dataset interactif$seed$, $seed$Interactive dataset$seed$,
  58, 'EUR',
  25,
  $seed$Valmy MABIKA$seed$,
  4.8,
  203,
  true,
  $seed$2026-05-10$seed$::timestamptz
),
(
  $seed$data-sql-2026-05-06$seed$,
  $seed$data$seed$, $seed$intermediate$seed$,
  $seed$SQL Avancé & Analyse de Données$seed$, $seed$Advanced SQL & Data Analysis$seed$,
  $seed$Fenêtres analytiques, CTEs, optimisation de requêtes, reporting et extraction d'insights sur des millions de lignes.$seed$, $seed$Analytic windows, CTEs, query optimization, reporting, and insight extraction on millions of rows.$seed$,
  $seed$[{"fr":"SQL basique","en":"Basic SQL"}]$seed$::jsonb,
  $seed${"kind":"code","content":"-- Classement des commerciaux par CA mensuel\nSELECT\n  nom,\n  mois,\n  ca,\n  RANK() OVER (\n    PARTITION BY mois\n    ORDER BY ca DESC\n  ) AS rang,\n  SUM(ca) OVER (PARTITION BY nom) AS ca_total_annuel\nFROM ventes\nWHERE annee = 2026\nORDER BY mois, rang;"}$seed$::jsonb,
  $seed$Requête avancée$seed$, $seed$Advanced query$seed$,
  43, 'EUR',
  22,
  $seed$Valmy MABIKA$seed$,
  4.7,
  331,
  true,
  $seed$2026-05-06$seed$::timestamptz
),
(
  $seed$data-powerbi-2026-03-25$seed$,
  $seed$data$seed$, $seed$beginner$seed$,
  $seed$Power BI : Dashboards Professionnels$seed$, $seed$Power BI: Professional Dashboards$seed$,
  $seed$Construisez des dashboards KPI dynamiques avec Power BI Desktop : connexions aux données, DAX et publication cloud.$seed$, $seed$Build dynamic KPI dashboards with Power BI Desktop: data connections, DAX formulas, and cloud publishing.$seed$,
  $seed$[{"fr":"Excel intermédiaire","en":"Intermediate Excel"}]$seed$::jsonb,
  $seed${"kind":"code","content":"// Mesures DAX pour KPIs métier\nCA Total = SUM(Ventes[Montant])\n\nCA Mois Précédent = \n  CALCULATE([CA Total],\n    PREVIOUSMONTH('Calendrier'[Date])\n  )\n\nÉvolution % = \n  DIVIDE(\n    [CA Total] - [CA Mois Précédent],\n    [CA Mois Précédent],\n    0\n  )"}$seed$::jsonb,
  $seed$Formule DAX$seed$, $seed$DAX formula$seed$,
  30, 'EUR',
  16,
  $seed$Valmy MABIKA$seed$,
  4.6,
  445,
  true,
  $seed$2026-03-25$seed$::timestamptz
),
(
  $seed$testing-selenium-2026-05-11$seed$,
  $seed$testing$seed$, $seed$intermediate$seed$,
  $seed$Selenium & Automatisation Web$seed$, $seed$Selenium & Web Automation$seed$,
  $seed$Stratégies de sélecteurs robustes, gestion des waits, tests stables et rapports HTML exploitables en CI/CD.$seed$, $seed$Robust selector strategies, wait management, stable tests, and CI/CD-friendly HTML reports.$seed$,
  $seed$[{"fr":"JS/TS ou Python","en":"JS/TS or Python"},{"fr":"Notions de QA","en":"QA basics"}]$seed$::jsonb,
  $seed${"kind":"runner","content":"// Scénario Selenium — login flow\ntest('login → dashboard redirect', async () => {\n  await page.goto('/auth');\n  await page.fill('#email', 'demo@site.com');\n  await page.fill('#password', 'Secure123!');\n  await page.click('button[type=submit]');\n  \n  // Attente explicite — jamais de sleep()\n  await page.waitForURL('/dashboard');\n  await expect(page.locator('h1')).toContainText('Dashboard');\n});"}$seed$::jsonb,
  $seed$Test case runner$seed$, $seed$Test case runner$seed$,
  37, 'EUR',
  18,
  $seed$Valmy MABIKA$seed$,
  4.7,
  142,
  true,
  $seed$2026-05-11$seed$::timestamptz
),
(
  $seed$testing-playwright-2026-05-12$seed$,
  $seed$testing$seed$, $seed$advanced$seed$,
  $seed$Playwright & Tests E2E Modernes$seed$, $seed$Playwright & Modern E2E Testing$seed$,
  $seed$Playwright de A à Z : Page Object Model, fixtures, tests parallèles, screenshots, vidéos et intégration CI complète.$seed$, $seed$Playwright from A to Z: Page Object Model, fixtures, parallel tests, screenshots, videos, and full CI integration.$seed$,
  $seed$[{"fr":"TypeScript","en":"TypeScript"},{"fr":"Tests unitaires","en":"Unit testing"}]$seed$::jsonb,
  $seed${"kind":"runner","content":"// Page Object Model avec Playwright\nexport class LoginPage {\n  constructor(private page: Page) {}\n\n  async login(email: string, password: string) {\n    await this.page.fill('[data-testid=email]', email);\n    await this.page.fill('[data-testid=password]', password);\n    await this.page.click('[data-testid=submit]');\n    await this.page.waitForURL('/dashboard');\n  }\n}\n\n// Test\ntest('login réussi', async ({ page }) => {\n  const login = new LoginPage(page);\n  await login.login('user@test.com', 'pass');\n});"}$seed$::jsonb,
  $seed$Page Object Model$seed$, $seed$Page Object Model$seed$,
  49, 'EUR',
  20,
  $seed$Valmy MABIKA$seed$,
  4.9,
  98,
  true,
  $seed$2026-05-12$seed$::timestamptz
)
on conflict (slug) do nothing;
