-- ============================================================================
-- SEED BLOG — migration des articles statiques du front vers Supabase.
-- Généré automatiquement depuis portfolio-frontend/src/data/blog.ts.
-- Idempotent : les slugs déjà présents sont ignorés.
-- ============================================================================

insert into public.blog_posts (
  slug, status,
  category_fr, category_en,
  title_fr, title_en,
  excerpt_fr, excerpt_en,
  content_fr, content_en,
  image_url, read_time, featured,
  author_id, published_at
) values
(
  'react-best-practices',
  'published',
  'Web Dev', 'Web Dev',
  'Les meilleures pratiques React en 2024', 'React Best Practices in 2024',
  'Hooks personnalisés, code splitting, memoization — un guide pratique pour écrire du React maintenable et performant.', 'Custom hooks, code splitting, memoization — a practical guide to writing maintainable, performant React.',
  '["React a considérablement évolué depuis ses débuts. Avec l''adoption généralisée des hooks et l''arrivée de React 19, certaines pratiques sont devenues incontournables pour écrire du code maintenable et performant.","Les hooks personnalisés constituent la première bonne pratique à adopter. Plutôt que de dupliquer de la logique entre composants, extraire cette logique dans un hook dédié (useCountUp, useIntersection, useDebounce...) simplifie les tests unitaires, facilite la réutilisation et améliore la lisibilité. Un hook bien nommé documente l''intention du code sans commentaire supplémentaire.","Le code splitting via React.lazy() et Suspense réduit le bundle initial de façon significative. Chaque route devrait être lazy-loadée — le navigateur ne charge que ce dont l''utilisateur a besoin. En combinant cela avec prefetch sur les liens hovered, on obtient une navigation quasi-instantanée tout en conservant un First Contentful Paint optimal.","Enfin, la memoization (useMemo, useCallback, React.memo) doit rester ciblée. L''appliquer partout est contre-productif — la comparaison de dépendances a un coût. Réservez-la aux calculs coûteux, aux tableaux/objets recréés à chaque render, et aux callbacks passés à des composants enfants optimisés.","Ces trois piliers — hooks personnalisés, code splitting et memoization ciblée — forment la base d''une architecture React solide. La clé est la consistance : appliquer ces principes systématiquement dès le début d''un projet est infiniment plus efficace que de les introduire a posteriori."]'::jsonb,
  '["React has evolved considerably since its early days. With the widespread adoption of hooks and the arrival of React 19, certain practices have become essential for writing maintainable and performant code.","Custom hooks are the first best practice to adopt. Rather than duplicating logic between components, extracting that logic into a dedicated hook (useCountUp, useIntersection, useDebounce...) simplifies unit testing, facilitates reuse and improves readability. A well-named hook documents the intent of the code without additional comments.","Code splitting via React.lazy() and Suspense significantly reduces the initial bundle. Each route should be lazy-loaded — the browser only loads what the user needs. Combined with prefetch on hovered links, this achieves near-instant navigation while maintaining an optimal First Contentful Paint.","Finally, memoization (useMemo, useCallback, React.memo) should remain targeted. Applying it everywhere is counterproductive — dependency comparison has a cost. Reserve it for expensive computations, arrays/objects recreated on every render, and callbacks passed to optimized child components.","These three pillars — custom hooks, code splitting and targeted memoization — form the foundation of a solid React architecture. The key is consistency: applying these principles systematically from the start of a project is infinitely more effective than introducing them after the fact."]'::jsonb,
  '/react_js_image.jpg',
  8,
  true,
  (select id from auth.users where email = 'valmymabika@gmail.com' limit 1),
  '2024-11-15'::timestamptz
),
(
  'playwright-automation',
  'published',
  'QA / Tests', 'QA / Testing',
  'Automatisation des tests avec Playwright', 'Test Automation with Playwright',
  'Comment mettre en place une suite de tests end-to-end robuste avec Playwright, CI/CD et GitHub Actions.', 'How to set up a robust end-to-end test suite with Playwright, CI/CD and GitHub Actions.',
  '["Playwright s''est imposé comme l''outil de référence pour les tests end-to-end. Sa capacité à cibler Chrome, Firefox et WebKit avec une seule API, combinée à son modèle d''attente automatique, en fait un choix solide pour les équipes qui veulent des tests fiables sans maintenance excessive.","La première étape est la stratégie de sélecteurs. Les data-testid sont préférables aux sélecteurs CSS fragiles — ils survivent aux refactorings visuels. Playwright recommande les rôles ARIA (getByRole, getByLabel) qui reflètent l''interface utilisateur telle qu''un utilisateur la perçoit, pas telle que le DOM la structure.","L''intégration CI/CD est ce qui transforme une suite de tests locale en filet de sécurité réel. Dans GitHub Actions, une configuration minimale suffit : checkout, install, playwright install --with-deps, puis npx playwright test. Les artifacts HTML (--reporter=html) permettent de déboguer les échecs visuellement, sans avoir à relancer les tests localement.","Le point souvent négligé : la gestion du flakiness. Les tests instables sont pires que l''absence de tests — ils érodent la confiance de l''équipe. Playwright offre plusieurs mécanismes : retry configurable par projet, soft assertions pour accumuler les erreurs, et trace viewer pour rejouer exactement ce qui s''est passé lors d''un échec.","Pour une suite de tests à long terme, organisez vos tests par flux métier plutôt que par composant technique. Un test qui valide ''l''utilisateur peut créer une facture'' est plus robuste et plus lisible qu''un test qui valide ''le bouton submit est visible''. Cette approche réduit la surface de maintenance et maximise la valeur de chaque test."]'::jsonb,
  '["Playwright has established itself as the reference tool for end-to-end testing. Its ability to target Chrome, Firefox and WebKit with a single API, combined with its auto-waiting model, makes it a solid choice for teams who want reliable tests without excessive maintenance.","The first step is selector strategy. data-testid attributes are preferable to fragile CSS selectors — they survive visual refactoring. Playwright recommends ARIA roles (getByRole, getByLabel) which reflect the user interface as a user perceives it, not as the DOM structures it.","CI/CD integration is what transforms a local test suite into a real safety net. In GitHub Actions, a minimal configuration is sufficient: checkout, install, playwright install --with-deps, then npx playwright test. HTML artifacts (--reporter=html) allow debugging failures visually, without having to re-run tests locally.","The often overlooked point: flakiness management. Unstable tests are worse than no tests — they erode team confidence. Playwright offers several mechanisms: configurable retry per project, soft assertions to accumulate errors, and trace viewer to replay exactly what happened during a failure.","For a long-term test suite, organize your tests by business flow rather than technical component. A test that validates ''the user can create an invoice'' is more robust and readable than a test that validates ''the submit button is visible''. This approach reduces maintenance surface and maximizes the value of each test."]'::jsonb,
  '/selenium_automatisation.png',
  12,
  true,
  (select id from auth.users where email = 'valmymabika@gmail.com' limit 1),
  '2024-10-28'::timestamptz
),
(
  'python-data-analysis',
  'published',
  'Data', 'Data',
  'Analyse de données avec Python et Pandas', 'Data Analysis with Python and Pandas',
  'Exploration, nettoyage, visualisation — les étapes clés pour transformer des données brutes en insights actionnables.', 'Exploration, cleaning, visualization — the key steps to transform raw data into actionable insights.',
  '["L''analyse de données suit un pipeline reproductible : exploration, nettoyage, transformation, visualisation, interprétation. Pandas facilite chacune de ces étapes, mais l''outil ne remplace pas la rigueur méthodologique. Un mauvais nettoyage produit de beaux graphiques sur des données fausses.","La phase d''exploration commence toujours par df.info(), df.describe() et df.isnull().sum(). Ces trois appels donnent une vue d''ensemble : types de colonnes, statistiques descriptives et taux de valeurs manquantes. C''est à partir de cette photo initiale qu''on décide de la stratégie de nettoyage.","Le nettoyage est l''étape la plus chronophage — elle représente souvent 60 à 70% du temps d''analyse. Les valeurs manquantes peuvent être imputées (médiane pour les numériques, mode pour les catégorielles) ou supprimées selon leur taux et leur importance. Les doublons se gèrent avec df.drop_duplicates(). Les types incorrects se corrigent avec astype() ou pd.to_datetime().","Pour la visualisation, Matplotlib et Seaborn couvrent 95% des besoins. La règle d''or : chaque graphique doit répondre à une question précise. Un histogramme pour la distribution, un boxplot pour les outliers, un scatter plot pour les corrélations, un heatmap pour la matrice de corrélation globale.","L''interprétation est ce qui différencie l''analyste du technicien. Les chiffres ne parlent pas seuls — ils doivent être contextualisés. Un taux de conversion de 3% est excellent dans l''e-commerce luxe, médiocre dans le SaaS B2B. Connaître le domaine métier est aussi important que maîtriser Pandas."]'::jsonb,
  '["Data analysis follows a reproducible pipeline: exploration, cleaning, transformation, visualization, interpretation. Pandas facilitates each of these steps, but the tool doesn''t replace methodological rigor. Poor cleaning produces beautiful charts on wrong data.","The exploration phase always starts with df.info(), df.describe() and df.isnull().sum(). These three calls give an overview: column types, descriptive statistics and missing value rates. It''s from this initial snapshot that we decide on the cleaning strategy.","Cleaning is the most time-consuming step — it often represents 60 to 70% of analysis time. Missing values can be imputed (median for numerics, mode for categoricals) or removed depending on their rate and importance. Duplicates are handled with df.drop_duplicates(). Incorrect types are corrected with astype() or pd.to_datetime().","For visualization, Matplotlib and Seaborn cover 95% of needs. The golden rule: each chart must answer a specific question. A histogram for distribution, a boxplot for outliers, a scatter plot for correlations, a heatmap for the global correlation matrix.","Interpretation is what differentiates the analyst from the technician. Numbers don''t speak for themselves — they need context. A 3% conversion rate is excellent in luxury e-commerce, mediocre in B2B SaaS. Knowing the business domain is as important as mastering Pandas."]'::jsonb,
  '/automatisation.jpg',
  10,
  false,
  (select id from auth.users where email = 'valmymabika@gmail.com' limit 1),
  '2024-09-12'::timestamptz
),
(
  'nestjs-api',
  'published',
  'Web Dev', 'Web Dev',
  'Construire une API REST avec NestJS', 'Building a REST API with NestJS',
  'Architecture modulaire, injection de dépendances, guards et interceptors — NestJS pour des APIs robustes.', 'Modular architecture, dependency injection, guards and interceptors — NestJS for robust APIs.',
  '["NestJS impose une structure qui fait défaut à Express : modules, contrôleurs, services, repositories. Cette organisation n''est pas une contrainte arbitraire — elle reflète les principes SOLID et rend le code testable par construction. Chaque module est une unité autonome avec ses dépendances déclarées explicitement.","L''injection de dépendances est le cœur de NestJS. Déclarer un service comme @Injectable() et l''injecter dans un contrôleur via le constructeur permet de remplacer n''importe quelle implémentation par un mock dans les tests. C''est la différence entre une suite de tests qui valide le comportement réel et une suite de tests qui valide des mocks.","Les Guards gèrent l''authentification et l''autorisation. Un JwtAuthGuard appliqué au niveau du contrôleur protège toutes ses routes — pas besoin de dupliquer la logique de vérification de token. Les Interceptors ajoutent une couche transversale : logging, transformation de réponse, cache. Un ResponseInterceptor normalise toutes les réponses API en un format cohérent.","Les Pipes valident et transforment les données d''entrée. Combinés à class-validator, ils éliminent la validation manuelle dans chaque handler. @IsEmail(), @IsNotEmpty(), @MinLength(8) sur le DTO — NestJS rejette automatiquement les requêtes invalides avec un message d''erreur structuré avant même d''atteindre le service.","Pour les projets de taille moyenne, NestJS peut sembler sur-dimensionné. Mais dès qu''une API dépasse 10 endpoints et implique plusieurs développeurs, la structure qu''il impose devient un avantage décisif. Le code est prévisible, testable, et un développeur qui rejoint l''équipe comprend l''architecture en 30 minutes."]'::jsonb,
  '["NestJS imposes a structure that Express lacks: modules, controllers, services, repositories. This organization is not an arbitrary constraint — it reflects SOLID principles and makes code testable by construction. Each module is an autonomous unit with its dependencies explicitly declared.","Dependency injection is at the heart of NestJS. Declaring a service as @Injectable() and injecting it into a controller via the constructor allows replacing any implementation with a mock in tests. This is the difference between a test suite that validates real behavior and one that validates mocks.","Guards handle authentication and authorization. A JwtAuthGuard applied at the controller level protects all its routes — no need to duplicate token verification logic. Interceptors add a cross-cutting layer: logging, response transformation, caching. A ResponseInterceptor normalizes all API responses into a consistent format.","Pipes validate and transform input data. Combined with class-validator, they eliminate manual validation in each handler. @IsEmail(), @IsNotEmpty(), @MinLength(8) on the DTO — NestJS automatically rejects invalid requests with a structured error message before even reaching the service.","For medium-sized projects, NestJS can seem over-engineered. But as soon as an API exceeds 10 endpoints and involves multiple developers, the structure it imposes becomes a decisive advantage. The code is predictable, testable, and a developer joining the team understands the architecture in 30 minutes."]'::jsonb,
  '/react_js_image.jpg',
  14,
  false,
  (select id from auth.users where email = 'valmymabika@gmail.com' limit 1),
  '2024-08-05'::timestamptz
),
(
  'freelance-tips',
  'published',
  'Carrière', 'Career',
  '5 conseils pour réussir en freelance tech', '5 Tips to Succeed as a Tech Freelancer',
  'Trouver des clients, fixer ses tarifs, gérer son temps — les leçons apprises après 3 ans de freelance.', 'Finding clients, setting rates, managing time — lessons learned after 3 years of freelancing.',
  '["Après 3 ans en freelance tech, voici les 5 leçons qui ont le plus transformé mon activité. Ce ne sont pas des théories — ce sont des pratiques éprouvées sur des projets réels.","1. Spécialisez-vous. Le généraliste freelance est en concurrence avec tout le monde. Le spécialiste React + tests automatisés est en concurrence avec personne (ou presque). Une niche claire rend le démarchage plus efficace, les tarifs plus justifiables et les clients mieux qualifiés.","2. Fixez vos tarifs selon la valeur, pas le temps. Un client ne vous paie pas pour vos heures — il vous paie pour résoudre son problème. Un développeur senior qui résout en 2h un problème qu''un junior mettrait 2 jours à résoudre doit facturer sa compétence, pas son temps passé.","3. Traitez chaque client comme un partenariat. Les clients qui renouvellent sont infiniment plus rentables que les nouveaux. Un suivi post-livraison, une documentation claire, une disponibilité réactive — ces détails construisent une réputation qui génère des recommandations sans démarchage.","4. Gérez votre énergie, pas seulement votre temps. Le freelance n''a pas de collègues pour absorber les tâches répétitives. Bloquez du temps pour la veille technique, les projets personnels et la récupération. L''épuisement est le risque numéro un du freelance — pas le manque de clients.","5. Contractualisez tout. Un scope clair, des livrables définis, des jalons de paiement explicites. Les litiges viennent presque toujours d''attentes non formalisées. Un contrat simple protège les deux parties et donne un cadre professionnel à la relation."]'::jsonb,
  '["After 3 years as a tech freelancer, here are the 5 lessons that most transformed my practice. These are not theories — they are proven practices on real projects.","1. Specialize. The generalist freelancer competes with everyone. The React + automated testing specialist competes with almost no one. A clear niche makes prospecting more efficient, rates more justifiable and clients better qualified.","2. Set your rates based on value, not time. A client doesn''t pay you for your hours — they pay you to solve their problem. A senior developer who solves in 2 hours a problem that a junior would take 2 days to solve should invoice their expertise, not their time spent.","3. Treat each client as a partnership. Clients who renew are infinitely more profitable than new ones. Post-delivery follow-up, clear documentation, responsive availability — these details build a reputation that generates recommendations without prospecting.","4. Manage your energy, not just your time. The freelancer has no colleagues to absorb repetitive tasks. Block time for technical monitoring, personal projects and recovery. Burnout is the number one risk for freelancers — not lack of clients.","5. Document everything contractually. Clear scope, defined deliverables, explicit payment milestones. Disputes almost always come from unformalized expectations. A simple contract protects both parties and gives a professional framework to the relationship."]'::jsonb,
  '/bureau.jpg',
  6,
  false,
  (select id from auth.users where email = 'valmymabika@gmail.com' limit 1),
  '2024-07-20'::timestamptz
),
(
  'docker-deployment',
  'published',
  'Automatisation', 'Automation',
  'Déploiement automatisé avec Docker et GitHub Actions', 'Automated Deployment with Docker & GitHub Actions',
  'Build, test, push, deploy — un pipeline complet pour automatiser la livraison de vos applications.', 'Build, test, push, deploy — a complete pipeline to automate your application delivery.',
  '["Un pipeline CI/CD bien conçu transforme le déploiement d''un acte risqué en opération routine. Docker + GitHub Actions constituent aujourd''hui la combinaison la plus accessible pour les projets de taille petite à moyenne.","Le Dockerfile est la première brique. Pour une application Node.js, un build multi-stage est la bonne pratique : une stage builder qui installe les dépendances et compile, une stage production qui ne contient que les artifacts nécessaires. Résultat : une image finale légère (souvent 3 à 5x plus petite) et sans surface d''attaque inutile.","Le workflow GitHub Actions suit une logique séquentielle : checkout du code, setup de l''environnement, exécution des tests, build de l''image Docker, push vers un registry (Docker Hub, GHCR, ou privé), puis déploiement. Chaque étape est conditionnée à la réussite de la précédente — un test qui échoue stoppe le pipeline avant que le code défectueux n''atteigne la production.","La gestion des secrets est critique. Les credentials (DOCKER_USERNAME, DOCKER_PASSWORD, SSH keys, API tokens) ne doivent jamais apparaître en clair dans le code. GitHub Secrets chiffre ces valeurs et les expose comme variables d''environnement uniquement lors de l''exécution du workflow.","Pour aller plus loin : les environnements GitHub (staging, production) permettent de définir des règles d''approbation manuelle avant le déploiement en production. Un reviewer doit approuver le déploiement — même si les tests passent. Cette étape de validation humaine, souvent omise, évite de nombreuses incidents en production."]'::jsonb,
  '["A well-designed CI/CD pipeline transforms deployment from a risky act to a routine operation. Docker + GitHub Actions are today the most accessible combination for small to medium-sized projects.","The Dockerfile is the first building block. For a Node.js application, a multi-stage build is best practice: a builder stage that installs dependencies and compiles, a production stage that only contains the necessary artifacts. Result: a lightweight final image (often 3 to 5x smaller) and without unnecessary attack surface.","The GitHub Actions workflow follows a sequential logic: checkout the code, setup the environment, run tests, build the Docker image, push to a registry (Docker Hub, GHCR, or private), then deploy. Each step is conditioned on the success of the previous one — a failing test stops the pipeline before the defective code reaches production.","Secret management is critical. Credentials (DOCKER_USERNAME, DOCKER_PASSWORD, SSH keys, API tokens) must never appear in plain text in the code. GitHub Secrets encrypts these values and exposes them as environment variables only during workflow execution.","To go further: GitHub environments (staging, production) allow defining manual approval rules before production deployment. A reviewer must approve the deployment — even if tests pass. This human validation step, often omitted, avoids many production incidents."]'::jsonb,
  '/automatisation.jpg',
  11,
  false,
  (select id from auth.users where email = 'valmymabika@gmail.com' limit 1),
  '2024-06-30'::timestamptz
)
on conflict (slug) do nothing;
